# name: Trigger Frontend Rebuild

# on:
#   push:
#     branches: [main]

# jobs:
#   trigger:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Trigger site-main rebuild
#         uses: peter-evans/repository-dispatch@v3
#         with:
#           token: ${{ secrets.PAT_TOKEN }}
#           repository: xiaojingming/site
#           event-type: blog-content-updated
